sudo: required
language: node_js
node_js:
- '6'
- node
sudo: required
services:
- docker
before_install:
- npm install -g npm@'>=2.13.5'
script:
- npm test
after_success:
  - if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then
    docker build -t xogroup/helm-chart-s3-publisher:latest -t xogroup/helm-chart-s3-publisher:$TRAVIS_TAG .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push xogroup/helm-chart-s3-publisher;
    echo "Built to DockerHub";
    else
    echo "Skipping deployment with the dockerhub provider because this is not a tagged commit";
    fi
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: q4BpuEvpKGmXA8uezilbFY2f1CliD5pEw85jp1lgOV75b/1rQ73JZpga5WiTTmKlb5LEfgVayWg4fnM8q8BXMIPmfpQ2FkJNIx0qi5lWZMV9ZsGOUVQF23YQ1mc9pTAu1zAThd8NvJlKhAHyeUZoaTpFbD61knESH+tAJNlPqlPDFj6Z2Z1DnqSkYt+m49vfBfy1Xkv9HcNgkk5egnfLvfdqycsyksgi4Yxofv9LCa9/UoXlACJfFwSsSr4M56OKjNHAk2pMLVNqxBvfIQuIvfKWq60ECyY63iQzv+21il7DnJZibPqztps6KvP07oe3FvkAPl+rhFLs+HeDq6aqqOS4SfZVIuWQPKWdICW1j2N04duC4HDyhqitZHc0txJXzvOBQNtM002Qmb2AAZwJLa1TXMpJKfV4sx8Qlk0Q4lVzPCGe5y5VQW2Ne3UgQ7HgO5fVfJJjnuNAsEiT6y7QViS5GhMi4YDGOAyExoWFkJ9rN60zxuXUxCS7B/TpfqsVzZFnY9Zm0FZ3PpblGfV9+8MzJxr9L4gSiyOBy+2HeISCHHOk0V9744+jzkeHBWCngCdPR4DGhqfDg7tvC7Z8rK6ZDkkm2R7dfp7Kf/0wU766RPnPzQ4/WTvJtC8Vmy+43HU1MXHeu45nrmVT3FVMV/+qIR2fu9HaJqM9QO6xUHQ=
  on:
    tags: true
    repo: xogroup/helm-chart-s3-publisher
notifications:
  slack:
    secure: I0R0m/Mz6pP7vZLaqRP3RwtaiI6lbpcfNpU1qUFMB4JgvHuqLEJyqUF/ayvph3wvCFeQTRkNX7Rot+II5kum71eM9T4yqxc/CBjDEoHFEVQ0G9sweeXMfZp1lukVyWnZXDgZSjTu8Ml7sItsEh8W5wJByjvvV2qdoBT8mn4kfAN+qAxLQUt5ZjsB13TLA3At16fGMPg170FCrtHsyLt2lfFW0bRhUvT8z1aTkn+7wuyVpamrt2l3PpJVgyJTUD0GuHUxBEIkv47fzSU/NmXFUw3e+Of8+AnB3LGFUK6CP42a50sbCKB7R0uWLLTXCDSaNLq6k3pu0lRytX0pTvZZR2hcki7VFbWMFl0FvKK7JAmQihJk9cxNY8URfpoNu7hXpeWXz+DU57MK/yYmwwmm/WxssFKuGmOgS1HU2n0sunB1OV9xJPu3yy7fr7raUZZvpJp8QRwWJIvBJprm0W+Oq6aDoagMZ/J5WCq/ThcnTmNBBFX+SlRfdzpq7NHtCB/TQeA61sl0+68G6YTIwtQ7ubIfT9EbMZgKCg6aUXSiOAXsT+JjPZEXk9CJURcxAihrvEKTh7Gs5rGMP27Zw8yT6N3uxrK5vitXuAkOXUdmZetbs1mBUrI+FVY21ey/gxTtLQlUTGPlf3DJvXBBpmjrZGlAHlit6zZQEENLgzxSfhA=
